### ISSUE TITLE
Configurable biases and offsets

### ISSUE THREAD

**Issue by CEngelbrecht** [twyatt/galactic-aztec-heavy-data-acquisition#6]
Hey Travis, in previous communication you'd mentioned possibly making the conversion values from mv/V to PSI a tweakable parameter from the client, so that you won't have to make a new client for every new calibration test of the ducers or phidget. Is that something that's still possible? RP would like to do more pressure transducer calibration in the near future.

Thanks again!
Christian Engelbrecht

**Comment by twyatt** [comment]
Sure thing. I'll try to find some time in the next week or two.

**Comment by twyatt** [comment]
@CEngelbrecht just wanted to keep you updated: made some progress on this. I hope to have something ready for you guys to test late next week (hopefully by March 24).

**Comment by CEngelbrecht** [comment]
Hey Travis, thanks for the update! We actually had the static test
yesterday. I'm going to start the data analysis today.

**Comment by twyatt** [comment]
@CEngelbrecht, been swamped lately and traveling next week. So I'll pick this up early April.

**Comment by twyatt** [comment]
@CEngelbrecht sorry, I had started this...but a year later and I never even checked in, shame on me. I have a partial (and basic) solution to this that I could find some time to wrap this up (if it is still needed?).

**Comment by CEngelbrecht** [comment]
Don't worry about this one Travis, we've been using other software! Thanks
for following up though

**Comment by twyatt** [comment]
Awesome, hope everything is going great and you guys are launching lots of rockets! 🚀

**Comment by CEngelbrecht** [comment]
We're in the middle of a pretty productive test campaign for testing a new
methane/lox engine, which is going very well! Should be launching mid next
semester! Check out our test videos
https://www.youtube.com/watch?v=L0jXDzVHpiI&t=2s
https://www.youtube.com/watch?v=m755FCPteYY
